# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Nightly Releases

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Nightly Builds
    
    strategy:
      matrix:
        kind: ["WINDOWS", "LINUX"]
        include:
        - kind: WINDOWS
          os: ubuntu-latest
          target: win-x64
        - kind: LINUX
          os: ubuntu-latest
          target: linux-x64
          
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
        
    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      shell: bash
      run: |
        # Define variables
        commit_hash=$(git rev-parse --short "$GITHUB_SHA")
        build_date=$(date +'%Y-%m-%d')
        release_name="RiftRipper-nightly-${build_date}.${commit_hash}.${{ matrix.target }}"
        echo "$release_name"
        
        # Build
        dotnet build RiftRipper/RiftRipper.csproj -c "${{ matrix.kind }}" -f "net7.0" -r "${{ matrix.target }}" -o "$release_name"
        wait
        
        # Publish
        dotnet publish RiftRipper/RiftRipper.csproj -c "${{ matrix.kind }}" -f "net7.0"  -r "${{ matrix.target }}" -o "$release_name"
        wait
        
        ls -R ../../
        wait
        
        # Pack files
        tar -czvf "${release_name}.tar.gz" "$release_name"
        wait
        
        # Delete output dir
        rm -r "$release_name"
        wait
      
    - name: Test
      run: dotnet test --no-build --verbosity normal
      
    - name: Publish
      uses: ncipollo/release-action@v1.12.0
      with:
        name: Nightly Builds
        tag: 'nightly'
        artifacts: RiftRipper-nightly-*.zip
        allowUpdates: true
        draft: false
        omitBodyDuringUpdate: true
        omitDraftDuringUpdate: true
        omitNameDuringUpdate: true
        prerelease: true
        replacesArtifacts: false
        skipIfReleaseExists: false
